<html>
<head>
   <title>Карта ракопок</title>
   
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
     integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
     crossorigin=""/>
   
   <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
     integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
     crossorigin=""></script>
   
   <script language="javascript">
      function init(map) {
                                
                
      	 L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
            maxZoom: 18
         }).addTo(map);
         map.attributionControl.setPrefix(''); // Don't show the 'Powered by Leaflet' text.

         //var london = new L.LatLng(51.5056,-0.1213); 
         var voronezh = new L.LatLng(51.67167,39.2105);
         map.setView(voronezh, 8);
         //https://habr.com/ru/articles/532902/
         
         // Define an array. This could be done in a seperate js file.
         // This tidy formatted section could even be generated by a server-side script
         // or fetched seperately as a jsonp request.
         
         //var markers = [
          //  [ -0.1244324, 51.5006728, "Big Ben" ],
        //    [ -0.119623, 51.503308, "London Eye" ],
         //   [ -0.1279688, 51.5077286, "Nelson's Column<br><a href=\"https://en.wikipedia.org/wiki/Nelson's_Column\">wp</a>" ] 
         //];
         
         //Loop through the markers array
         //for (var i=0; i<markers.length; i++) {
           
          //  var lon = markers[i][0];
            //var lat = markers[i][1];
            //var popupText = markers[i][2];
            
             //var markerLocation = new L.LatLng(lat, lon);
             //var marker = new L.Marker(markerLocation);
             //map.addLayer(marker);
         
             //marker.bindPopup(popupText);
         
         //}
         
            var markerLocation = new L.LatLng(50.6714087,40.0354686);
            var marker = new L.Marker(markerLocation);
            marker.bindPopup('с. Лосево Павловский р-н Воронежской области');
            map.addLayer(marker);
            //return map;

      }
        
    /*async function getPositionByName(query) {
        //alert(`https://nominatim.openstreetmap.org/search?q=${query}&format=json&limit=1`);
        const trueQuery = 'с. Лосево, Павловский район, Воронежская область';
        const response = await fetch(
         `https://nominatim.openstreetmap.org/search?q=${trueQuery}&format=json&limit=1`
        );
        // format - формат данных, limit - количество объектов с данными

        // парсим ответ, извлекая нужные сведения
        const { display_name, lat, lon } = (await response.json())[0];

        // редактриуем название объекта
        const name = display_name.match(/[А-ЯЁа-яё\s(«\-»)]+/)[0];

        const position = [lat, lon];
        //alert(position);
        return position;
        }*/
   </script>
   
</head>
<body onLoad="map0 = new L.Map('map'); 
    init(map0);">
    <?php
    include "cardMenu.html";
    session_start();
    $login = $_SESSION['inputLogin'];
    $password = $_SESSION['inputPassword'];
    
    $objectPositions = [];
    
    if(isset($login, $password)){
	//echo "start <br/>";
	$conn = pg_connect("host=pg3.sweb.ru port=5432 dbname=avkuzbkru user=".$login." password=".$password);
	if (!$conn) {
		echo "Ошибка подключения к БД.\n";
		echo "Возможно, необходима <a href=\"authentificationForm.php\">авторизация</a>\n";
		exit;
	}

	else{

		$objectsGeoStat = "SELECT \"Дата раскопок\", \"Доп. информация о месте\" FROM card_legacy WHERE (\"Дата раскопок\" IS NOT NULL AND \"Дата раскопок\" <> '');";
		$resGeo = pg_query($conn, $objectsGeoStat);
	if (!$resGeo) {
		echo "query error occurred.\n";
		exit;
	}
		while ($objectGeo = pg_fetch_row($resGeo)) {
  			//$objectPositions[] = $objectGeo[1];
  			$objectPositions[] = [$objectGeo[0],json_decode($objectGeo[1],true)];
  			//echo "<br />\n";
		}
		pg_close($conn);
	}
}
else {
	echo "Не заданы пароль и логин.\n";
	echo "Возможно, необходима <a href=\"authentificationForm.php\">авторизация</a>\n";
}
?>
   <div id="map" style="height: 80%"></div>
    <script language="javascript">
    //var namePosition = await getPositionByName('<?=$objectPositions[0][0]?>');
    function placeMarkers(map){
        
        <?php
        for($i = 0; $i < count($objectPositions); $i++)
        {
        echo 'var markerLocation = new L.LatLng('.$objectPositions[$i][1][0]['geo_lat'].','.$objectPositions[$i][1][0]['geo_lon'].');
        //alert(markerLocation);
        var marker = new L.Marker(markerLocation);
        marker.bindPopup("'.$objectPositions[$i][0].'");
        map.addLayer(marker);';
        }
        ?>
    }
   </script>
   <button onclick="placeMarkers(map0)">Показать раскопки</button>
   
</body>                                                                                                                          
</html>
